### ISSUE TITLE
TypeError: Python type 'str' is not supported as a Q_ARG() type

### ISSUE THREAD

**Issue by zhanglei2015yy** [niuzaisheng/ScreenAgent#14]
run in conda enviroment , python=3.8, got below issue:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "d:\Users\FELIX\anaconda3\envs\ScreenAgent38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d:\Users\FELIX\anaconda3\envs\ScreenAgent38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\My Project\GCC\Refer\ScreenAgent-main\client\interface_api\gpt4_client.py", line 74, in thread_func
    ask_llm_recall_func(response, fail_message, request_id)
  File "D:\My Project\GCC\Refer\ScreenAgent-main\client\controller_core.py", line 459, in _send_to_main_ask_llm_sync_recall_func
    QMetaObject.invokeMethod(self, "ask_llm_sync_recall_func", Qt.QueuedConnection, Q_ARG(str, response), Q_ARG(str, fail_message), Q_ARG(str, request_id))
TypeError: Python type 'str' is not supported as a Q_ARG() type

**Comment by niuzaisheng** [comment]
请检查一下模型推理或者API是否运行正常，这个报错是由于send_request_to_server没有拿到正确的回复输出。
