### ISSUE TITLE
Windows Run error 

### ISSUE THREAD

**Issue by 276585877** [niuzaisheng/ScreenAgent#30]
"./saved_models/ScreenAgent-2312" --bf16 --max_length 2048 RANK=0 WORLD_SIZE=1 LOCAL_RANK=0
[2024-09-03 15:43:27,153] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
[2024-09-03 15:43:28,770] [WARNING] DeepSpeed Not Installed, you cannot import training_main from sat now.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.4.0+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Please 'pip install apex'
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
Traceback (most recent call last):
  File "Z:\D\automation\ScreenAgent-main\train\cogagent_model_worker.py", line 20, in <module>
    from utils import chat, llama2_tokenizer, llama2_text_processor_inference, get_image_processor
  File "Z:\D\automation\ScreenAgent-main\train\utils\__init__.py", line 2, in <module>
    from .language import llama2_tokenizer, llama2_text_processor, llama2_text_processor_inference
  File "Z:\D\automation\ScreenAgent-main\train\utils\language.py", line 1, in <module>
    from sat.model.official.llama_model import LLaMAModel, rotate_half
ImportError: cannot import name 'rotate_half' from 'sat.model.official.llama_model' (C:\Users\comma\AppData\Local\Programs\Python\Python310\lib\site-packages\sat\model\official\llama_model.py)

**Comment by 276585877** [comment]
set RANK=0   && set LOCAL_WORLD_SIZE=1   && set LOCAL_RANK=0   && python ./cogagent_model_worker.py --host 0.0.0.0  --port 40000 --from_pretrained "./saved_models/ScreenAgent-2312" --bf16 --max_length 2048
[2024-09-04 10:04:16,616] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
[2024-09-04 10:04:19,245] [WARNING] DeepSpeed Not Installed, you cannot import training_main from sat now.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.3.0+cu118)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Please 'pip install apex'
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
2024-09-04 10:04:22 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, max_length=2048, top_p=0.4, top_k=1, temperature=0.8, chinese=False, version='chat', quant=None, stream_chat=False, from_pretrained='./saved_models/ScreenAgent-2312', local_tokenizer='lmsys/vicuna-7b-v1.5', fp16=False, bf16=True)
[2024-09-04 10:04:22,783] [INFO] building FineTuneTrainCogAgentModel model ...
2024-09-04 10:04:22 | INFO | sat | building FineTuneTrainCogAgentModel model ...
[2024-09-04 10:04:22,812] [INFO] [RANK 0] > initializing model parallel with size 1
2024-09-04 10:04:22 | INFO | sat | [RANK 0] > initializing model parallel with size 1
[2024-09-04 10:04:22,820] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
2024-09-04 10:04:22 | INFO | sat | [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.

运行一会就退出了，符合预期么

**Comment by wldst** [comment]
Please 'pip install apex'，你的以来还没有装，不过我的也没没有装好
